import Head from "next/head";

import axios from "configs/axios";

function Home(props) {
  console.log(props);
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Online Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Halaman Utama</main>
    </div>
  );
}

Home.getInitialProps = async () => {
  try {
    const data = await axios.get(`/courses`);
    console.log(data);
    return { data: data.data };
  } catch (error) {
    return error;
  }
};

export default Home;
