import Head from "next/head";

export default function Home() {
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Online Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Halaman Utama</main>
    </div>
  );
}
